# Generated by Django 3.2.15 on 2022-10-04 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20221004_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время заказа'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
