# Generated by Django 3.2.15 on 2022-10-04 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20221004_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment',
            field=models.CharField(choices=[('not specified', 'Не указан'), ('cash', 'Наличными'), ('card', 'Картой')], db_index=True, default='not specified', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='called_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время и дата звонка'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время и дата доставки'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время и дата заказа'),
        ),
    ]
