# Generated by Django 3.2.15 on 2022-10-06 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20221004_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='foodcartapp.restaurant', verbose_name='Кто приготовит'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment',
            field=models.CharField(choices=[('not specified', 'Не указан'), ('cash', 'Наличными'), ('card', 'Картой')], db_index=True, default='not specified', max_length=15, verbose_name='Способ оплаты'),
        ),
    ]
