# Generated by Django 3.2.15 on 2022-11-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_auto_20221102_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='customer',
            new_name='order',
        ),
    ]
