# Generated by Django 3.2.15 on 2022-11-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_auto_20221102_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('raw', 'Необработанный'), ('prepare', 'Готовиться'), ('delivered', 'Передан курьеру'), ('completed', 'Выполнен')], db_index=True, default='raw', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
