# Generated by Django 3.2.15 on 2022-10-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(unique=True, verbose_name='Широта')),
                ('longirude', models.FloatField(unique=True, verbose_name='Долгота')),
                ('address', models.CharField(blank=True, max_length=100, unique=True, verbose_name='адрес ресторана')),
                ('date', models.DateTimeField(unique=True, verbose_name='Дата запроса')),
            ],
        ),
    ]
