# Generated by Django 3.2.15 on 2022-11-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(unique=True, verbose_name='Широта')),
                ('longitude', models.FloatField(unique=True, verbose_name='Долгота')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='адрес ресторана')),
                ('requested_at', models.DateTimeField(verbose_name='Дата запроса')),
            ],
            options={
                'verbose_name': 'Месторасположение ресторана',
                'verbose_name_plural': 'Месторасположение ресторанов',
            },
        ),
    ]
