# Generated by Django 3.2.15 on 2022-10-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocode',
            name='address',
            field=models.CharField(max_length=100, unique=True, verbose_name='адрес ресторана'),
        ),
    ]
