# Generated by Django 3.2.15 on 2022-10-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocoderapp', '0002_alter_geocode_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geocode',
            options={'verbose_name': 'Месторасположение ресторана'},
        ),
        migrations.RenameField(
            model_name='geocode',
            old_name='longirude',
            new_name='longitude',
        ),
    ]
